// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreetServcie_SayHello_FullMethodName                = "/greet_service.GreetServcie/SayHello"
	GreetServcie_SayHelloServerStreaming_FullMethodName = "/greet_service.GreetServcie/SayHelloServerStreaming"
	GreetServcie_SayhelloClientStreaming_FullMethodName = "/greet_service.GreetServcie/SayhelloClientStreaming"
	GreetServcie_SayhelloclientStreaming_FullMethodName = "/greet_service.GreetServcie/SayhelloclientStreaming"
)

// GreetServcieClient is the client API for GreetServcie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetServcieClient interface {
	SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error)
	SayHelloServerStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloResponse], error)
	SayhelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloRequest, MessagesList], error)
	SayhelloclientStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloRequest, MessagesList], error)
}

type greetServcieClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServcieClient(cc grpc.ClientConnInterface) GreetServcieClient {
	return &greetServcieClient{cc}
}

func (c *greetServcieClient) SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GreetServcie_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServcieClient) SayHelloServerStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GreetServcie_ServiceDesc.Streams[0], GreetServcie_SayHelloServerStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NamesList, HelloResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GreetServcie_SayHelloServerStreamingClient = grpc.ServerStreamingClient[HelloResponse]

func (c *greetServcieClient) SayhelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloRequest, MessagesList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GreetServcie_ServiceDesc.Streams[1], GreetServcie_SayhelloClientStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloRequest, MessagesList]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GreetServcie_SayhelloClientStreamingClient = grpc.ClientStreamingClient[HelloRequest, MessagesList]

func (c *greetServcieClient) SayhelloclientStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloRequest, MessagesList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GreetServcie_ServiceDesc.Streams[2], GreetServcie_SayhelloclientStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloRequest, MessagesList]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GreetServcie_SayhelloclientStreamingClient = grpc.ClientStreamingClient[HelloRequest, MessagesList]

// GreetServcieServer is the server API for GreetServcie service.
// All implementations must embed UnimplementedGreetServcieServer
// for forward compatibility.
type GreetServcieServer interface {
	SayHello(context.Context, *NoParam) (*HelloResponse, error)
	SayHelloServerStreaming(*NamesList, grpc.ServerStreamingServer[HelloResponse]) error
	SayhelloClientStreaming(grpc.ClientStreamingServer[HelloRequest, MessagesList]) error
	SayhelloclientStreaming(grpc.ClientStreamingServer[HelloRequest, MessagesList]) error
	mustEmbedUnimplementedGreetServcieServer()
}

// UnimplementedGreetServcieServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreetServcieServer struct{}

func (UnimplementedGreetServcieServer) SayHello(context.Context, *NoParam) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetServcieServer) SayHelloServerStreaming(*NamesList, grpc.ServerStreamingServer[HelloResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloServerStreaming not implemented")
}
func (UnimplementedGreetServcieServer) SayhelloClientStreaming(grpc.ClientStreamingServer[HelloRequest, MessagesList]) error {
	return status.Errorf(codes.Unimplemented, "method SayhelloClientStreaming not implemented")
}
func (UnimplementedGreetServcieServer) SayhelloclientStreaming(grpc.ClientStreamingServer[HelloRequest, MessagesList]) error {
	return status.Errorf(codes.Unimplemented, "method SayhelloclientStreaming not implemented")
}
func (UnimplementedGreetServcieServer) mustEmbedUnimplementedGreetServcieServer() {}
func (UnimplementedGreetServcieServer) testEmbeddedByValue()                      {}

// UnsafeGreetServcieServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServcieServer will
// result in compilation errors.
type UnsafeGreetServcieServer interface {
	mustEmbedUnimplementedGreetServcieServer()
}

func RegisterGreetServcieServer(s grpc.ServiceRegistrar, srv GreetServcieServer) {
	// If the following call pancis, it indicates UnimplementedGreetServcieServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreetServcie_ServiceDesc, srv)
}

func _GreetServcie_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServcieServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetServcie_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServcieServer).SayHello(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetServcie_SayHelloServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NamesList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServcieServer).SayHelloServerStreaming(m, &grpc.GenericServerStream[NamesList, HelloResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GreetServcie_SayHelloServerStreamingServer = grpc.ServerStreamingServer[HelloResponse]

func _GreetServcie_SayhelloClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServcieServer).SayhelloClientStreaming(&grpc.GenericServerStream[HelloRequest, MessagesList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GreetServcie_SayhelloClientStreamingServer = grpc.ClientStreamingServer[HelloRequest, MessagesList]

func _GreetServcie_SayhelloclientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServcieServer).SayhelloclientStreaming(&grpc.GenericServerStream[HelloRequest, MessagesList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GreetServcie_SayhelloclientStreamingServer = grpc.ClientStreamingServer[HelloRequest, MessagesList]

// GreetServcie_ServiceDesc is the grpc.ServiceDesc for GreetServcie service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetServcie_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet_service.GreetServcie",
	HandlerType: (*GreetServcieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetServcie_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloServerStreaming",
			Handler:       _GreetServcie_SayHelloServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayhelloClientStreaming",
			Handler:       _GreetServcie_SayhelloClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayhelloclientStreaming",
			Handler:       _GreetServcie_SayhelloclientStreaming_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
